name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    env:
      DOCKER_DEFAULT_PLATFORM: linux/arm64
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [arm64]
    steps:
      - name: Install Qemu
        run: |
          sudo apt-get update -q -y
          sudo apt-get -qq install -y qemu qemu-user-static
      - uses: actions/checkout@v2
      - run: docker run --rm --platform linux/arm64 -v $(pwd):/root/go-ethereum --workdir=/root/go-ethereum/cmd/geth arm64v8/golang:1.17-bullseye go build
      - run: docker run --rm --platform linux/arm64 -v $(pwd):/root/go-ethereum --workdir=/root/go-ethereum/cmd/geth arm64v8/golang:1.17-bullseye /root/go-ethereum/cmd/geth/geth version
